// =====================================================
// AVENTURE-SE — Mock Data Provider
// Dados completos da viagem Réveillon Ubatuba 2026/2027
// =====================================================

import { Trip, TripAccommodation, TripTransportOption, TripImage, Coupon, Booking } from '@/types';

// ---- VIAGEM: Réveillon Aventure-se 2026/2027 ----

export const MOCK_TRIP_IMAGES: TripImage[] = [
  {
    id: 'img-001',
    trip_id: 'trip-reveillon-2026',
    image_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80',
    alt_text: 'Praia de Ubatumirim ao pôr do sol',
    order_index: 0,
    created_at: '2026-08-01T00:00:00Z',
  },
  {
    id: 'img-002',
    trip_id: 'trip-reveillon-2026',
    image_url: 'https://images.unsplash.com/photo-1506929562872-bb421503ef21?w=1200&q=80',
    alt_text: 'Festa na praia ao pôr do sol',
    order_index: 1,
    created_at: '2026-08-01T00:00:00Z',
  },
  {
    id: 'img-003',
    trip_id: 'trip-reveillon-2026',
    image_url: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200&q=80',
    alt_text: 'Yoga na praia ao amanhecer',
    order_index: 2,
    created_at: '2026-08-01T00:00:00Z',
  },
  {
    id: 'img-004',
    trip_id: 'trip-reveillon-2026',
    image_url: 'https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?w=1200&q=80',
    alt_text: 'Camping de frente para o mar',
    order_index: 3,
    created_at: '2026-08-01T00:00:00Z',
  },
  {
    id: 'img-005',
    trip_id: 'trip-reveillon-2026',
    image_url: 'https://images.unsplash.com/photo-1530053969600-caed2596d242?w=1200&q=80',
    alt_text: 'Fogos de artifício na virada do ano',
    order_index: 4,
    created_at: '2026-08-01T00:00:00Z',
  },
  {
    id: 'img-006',
    trip_id: 'trip-reveillon-2026',
    image_url: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=1200&q=80',
    alt_text: 'Praia paradisíaca em Ubatuba',
    order_index: 5,
    created_at: '2026-08-01T00:00:00Z',
  },
];

export const MOCK_ACCOMMODATIONS: TripAccommodation[] = [
  {
    id: 'acc-camping',
    trip_id: 'trip-reveillon-2026',
    type: 'camping',
    label: 'Camping Aventure-se',
    description: 'Camping exclusivo para o nosso grupo e de frente para o mar, em área sombreada e com estrutura pé na areia. Conta com cozinha e geladeira, pontos de energia, desembarque próximo, facilidade para bagagens e possibilidade de estacionar e acampar no mesmo local para quem for de carro. É a escolha para quem quer viver Ubatumirim ainda mais conectado à natureza.',
    amenities: ['De frente para o mar', 'Área sombreada', 'Cozinha e geladeira', 'Pontos de energia', 'Estacionamento junto à barraca'],
    price: 890,
    capacity: 60,
    booked_count: 42,
    check_in: null,
    check_out: null,
    created_at: '2026-08-01T00:00:00Z',
  },
  {
    id: 'acc-pousada',
    trip_id: 'trip-reveillon-2026',
    type: 'hostel',
    label: 'Pousada',
    description: 'Quartos para 2, 3 ou 4 pessoas com ar-condicionado, frigobar, roupa de cama, cama de casal + beliche, café da manhã, piscina, restaurante e estrutura de apoio na praia. Conforto e praticidade sem sair da experiência.',
    amenities: ['Ar-condicionado', 'Frigobar', 'Roupa de cama', 'Cama de casal + beliche', 'Café da manhã', 'Piscina', 'Restaurante', 'Estrutura de apoio na praia'],
    price: 1490,
    capacity: 40,
    booked_count: 31,
    check_in: '12:00',
    check_out: '11:00',
    created_at: '2026-08-01T00:00:00Z',
  },
  {
    id: 'acc-suite',
    trip_id: 'trip-reveillon-2026',
    type: 'suite',
    label: 'Suíte Master',
    description: 'Nossa categoria de maior conforto e privacidade, para até 4 pessoas. Ar-condicionado, frigobar, cama de casal + 2 camas auxiliares, banheiro com ducha quente, cozinha completa compartilhada entre os apartamentos, churrasqueira, fogão, forno, micro-ondas, geladeiras e freezer. A pousada e as Suítes Master ficam próximas da estrutura principal do evento.',
    amenities: ['Ar-condicionado', 'Frigobar', 'Cama de casal + 2 camas auxiliares', 'Banheiro com ducha quente', 'Cozinha completa compartilhada', 'Churrasqueira', 'Fogão e forno', 'Micro-ondas', 'Geladeiras e freezer'],
    price: 1990,
    capacity: 20,
    booked_count: 14,
    check_in: '10:00',
    check_out: '11:00',
    created_at: '2026-08-01T00:00:00Z',
  },
];

export const MOCK_TRANSPORT_OPTIONS: TripTransportOption[] = [
  {
    id: 'trp-with',
    trip_id: 'trip-reveillon-2026',
    label: 'Transporte Ida e Volta',
    description: 'Ida e volta saindo do Rio de Janeiro, com chegada próxima às hospedagens para tornar toda a logística mais simples.',
    origin: 'Rio de Janeiro',
    has_transport: true,
    price: 280,
    capacity: 44,
    booked_count: 28,
    created_at: '2026-08-01T00:00:00Z',
  },
  {
    id: 'trp-without',
    trip_id: 'trip-reveillon-2026',
    label: 'Ir por conta própria',
    description: 'Você irá por conta própria (carro, carona ou outro meio).',
    origin: '',
    has_transport: false,
    price: 0,
    capacity: 999,
    booked_count: 0,
    created_at: '2026-08-01T00:00:00Z',
  },
];

export const MOCK_TRIPS: Trip[] = [
  {
    id: 'trip-reveillon-2026',
    title: 'Réveillon Aventure-se 2026/2027',
    slug: 'reveillon-ubatuba-2026',
    destination: 'Ubatumirim, Ubatuba',
    location: 'Ubatumirim, Ubatuba - SP',
    start_date: '2026-12-29',
    end_date: '2027-01-03',
    description: `A noite é reflexo do dia.

Por isso, esse Réveillon começa muito antes da meia-noite.

Serão 5 dias pé na areia para sair do automático, cuidar do corpo, respirar, se movimentar, conhecer pessoas, viver a natureza e recuperar energia.

Durante o dia, o Aventure-se ganha uma experiência ainda mais voltada ao bem-estar, com Yoga, Breathwork, Acro Yoga, Futevôlei, Circuito Funcional, Massagem Tailandesa, caminhada, mar, momentos de presença e microexperiências sensoriais.

Quando o sol se põe, a energia muda.

São 4 festas temáticas, música, encontros, surpresas e aquela conexão que faz cada edição ganhar uma história própria.

Durante o dia, a gente cuida. À noite, a gente celebra.

Um novo ano começa antes da contagem regressiva.

Talvez você venha pela praia. Talvez pelas festas. Talvez pelas experiências. Ou talvez esteja simplesmente precisando de alguns dias para respirar e sentir a vida acontecendo de novo.

No fim, não importa apenas como você chega em Ubatumirim. Importa como você volta.

Corpo em movimento. Mente presente. Gente de verdade. Natureza. Música. Celebração.

A verdadeira virada começa dentro da gente. A meia-noite só celebra.`,
    highlights: [
      '5 dias de experiência em Ubatumirim',
      '4 festas temáticas pé na areia',
      'Yoga e Breathwork',
      'AcroYoga',
      'Futevôlei',
      'Circuito Funcional',
      'Massagem Tailandesa',
      'Experiências de bem-estar e conexão',
      'Microexperiências sensoriais',
      'Ritual especial da Virada',
      'Surpresas Aventure-se',
      'Seguro viagem',
    ],
    not_included: [
      'Alimentação (exceto café da manhã na Pousada)',
      'Bebidas',
      'Despesas pessoais',
      'Ingressos para atividades opcionais externas',
    ],
    itinerary: [
      { day: 1, title: 'Chegada & Boas-vindas', description: 'Recepção em Ubatumirim, check-in nas hospedagens, integração do grupo e primeira sunset session na praia.' },
      { day: 2, title: 'Corpo & Natureza', description: 'Yoga ao amanhecer, Breathwork, Circuito Funcional na areia, tarde livre no mar e primeira festa temática à noite.' },
      { day: 3, title: 'Aventura & Conexão', description: 'AcroYoga, Futevôlei, Massagem Tailandesa, microexperiências sensoriais e segunda festa temática.' },
      { day: 4, title: 'Virada do Ano', description: 'Manhã de bem-estar, tarde de preparação, Ritual especial da Virada e festa de Réveillon pé na areia.' },
      { day: 5, title: 'Renovação & Despedida', description: 'Yoga de encerramento, brunch coletivo, troca de contatos e despedida com o coração cheio.' },
    ],
    difficulty: 'leve',
    cover_image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80',
    is_active: true,
    is_featured: true,
    status: 'active',
    min_age: 18,
    meeting_point: 'Rio de Janeiro - Ponto a definir',
    meeting_time: '06:00',
    created_at: '2026-08-01T00:00:00Z',
    updated_at: '2026-08-01T00:00:00Z',
    accommodations: MOCK_ACCOMMODATIONS,
    transport_options: MOCK_TRANSPORT_OPTIONS,
    images: MOCK_TRIP_IMAGES,
  },
  {
    id: 'trip-chapada-2027',
    title: 'Expedição Chapada dos Veadeiros',
    slug: 'expedicao-chapada-dos-veadeiros',
    destination: 'Alto Paraíso de Goiás',
    location: 'Alto Paraíso de Goiás - GO',
    start_date: '2027-03-15',
    end_date: '2027-03-22',
    description: 'Uma imersão de 7 dias no coração do cerrado brasileiro, com trilhas por cachoeiras incríveis, banhos em poços naturais de águas cristalinas, noites estreladas e uma conexão profunda com a natureza do Planalto Central.',
    highlights: [
      '7 dias de imersão na Chapada',
      'Trilhas guiadas por cachoeiras',
      'Banhos em poços naturais',
      'Noites de observação de estrelas',
      'Gastronomia regional',
      'Guia credenciado',
      'Seguro aventura',
    ],
    not_included: ['Alimentação', 'Bebidas', 'Despesas pessoais'],
    itinerary: [],
    difficulty: 'moderado',
    cover_image: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1200&q=80',
    is_active: true,
    is_featured: false,
    status: 'active',
    min_age: 18,
    meeting_point: 'Brasília - Aeroporto',
    meeting_time: '08:00',
    created_at: '2026-08-10T00:00:00Z',
    updated_at: '2026-08-10T00:00:00Z',
    accommodations: [
      {
        id: 'acc-chapada-camping',
        trip_id: 'trip-chapada-2027',
        type: 'camping',
        label: 'Camping Aventure-se',
        description: 'Camping exclusivo em meio à natureza da Chapada.',
        amenities: ['Área de camping', 'Banheiros compartilhados', 'Cozinha comunitária'],
        price: 1290,
        capacity: 30,
        booked_count: 8,
        check_in: null,
        check_out: null,
        created_at: '2026-08-10T00:00:00Z',
      },
      {
        id: 'acc-chapada-pousada',
        trip_id: 'trip-chapada-2027',
        type: 'hostel',
        label: 'Pousada',
        description: 'Pousada aconchegante no centro de Alto Paraíso.',
        amenities: ['Ar-condicionado', 'Café da manhã', 'Wi-Fi', 'Piscina'],
        price: 2190,
        capacity: 20,
        booked_count: 5,
        check_in: '14:00',
        check_out: '11:00',
        created_at: '2026-08-10T00:00:00Z',
      },
    ],
    transport_options: [
      {
        id: 'trp-chapada-with',
        trip_id: 'trip-chapada-2027',
        label: 'Transfer Aeroporto + Chapada',
        description: 'Transfer do aeroporto de Brasília até Alto Paraíso de Goiás.',
        origin: 'Brasília',
        has_transport: true,
        price: 350,
        capacity: 30,
        booked_count: 10,
        created_at: '2026-08-10T00:00:00Z',
      },
      {
        id: 'trp-chapada-without',
        trip_id: 'trip-chapada-2027',
        label: 'Ir por conta própria',
        description: 'Você irá por conta própria.',
        origin: '',
        has_transport: false,
        price: 0,
        capacity: 999,
        booked_count: 0,
        created_at: '2026-08-10T00:00:00Z',
      },
    ],
    images: [
      {
        id: 'img-chapada-001',
        trip_id: 'trip-chapada-2027',
        image_url: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1200&q=80',
        alt_text: 'Cachoeira na Chapada dos Veadeiros',
        order_index: 0,
        created_at: '2026-08-10T00:00:00Z',
      },
    ],
  },
  {
    id: 'trip-jericoacoara-2027',
    title: 'Jericoacoara Experience',
    slug: 'jericoacoara-experience',
    destination: 'Jericoacoara',
    location: 'Jericoacoara - CE',
    start_date: '2027-05-01',
    end_date: '2027-05-07',
    description: 'Uma semana inesquecível nas dunas e lagoas de Jericoacoara, com kitesurf, passeios de buggy, pôr do sol na Duna do Pôr do Sol e muito mais.',
    highlights: [
      '6 noites em Jericoacoara',
      'Passeio de buggy pelas dunas',
      'Kitesurf (aula inclusa)',
      'Lagoa do Paraíso',
      'Pôr do sol na Duna',
      'Seguro aventura',
    ],
    not_included: ['Alimentação', 'Bebidas', 'Despesas pessoais'],
    itinerary: [],
    difficulty: 'leve',
    cover_image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200&q=80',
    is_active: true,
    is_featured: false,
    status: 'active',
    min_age: 18,
    meeting_point: 'Fortaleza - Aeroporto',
    meeting_time: '07:00',
    created_at: '2026-08-12T00:00:00Z',
    updated_at: '2026-08-12T00:00:00Z',
    accommodations: [
      {
        id: 'acc-jeri-pousada',
        trip_id: 'trip-jericoacoara-2027',
        type: 'hostel',
        label: 'Pousada',
        description: 'Pousada charmosa na vila de Jericoacoara.',
        amenities: ['Ar-condicionado', 'Café da manhã', 'Wi-Fi', 'Rede na varanda'],
        price: 2490,
        capacity: 24,
        booked_count: 20,
        check_in: '14:00',
        check_out: '12:00',
        created_at: '2026-08-12T00:00:00Z',
      },
    ],
    transport_options: [
      {
        id: 'trp-jeri-with',
        trip_id: 'trip-jericoacoara-2027',
        label: 'Transfer Fortaleza - Jeri',
        description: 'Transfer do aeroporto de Fortaleza até Jericoacoara.',
        origin: 'Fortaleza',
        has_transport: true,
        price: 190,
        capacity: 24,
        booked_count: 18,
        created_at: '2026-08-12T00:00:00Z',
      },
      {
        id: 'trp-jeri-without',
        trip_id: 'trip-jericoacoara-2027',
        label: 'Ir por conta própria',
        description: 'Você irá por conta própria.',
        origin: '',
        has_transport: false,
        price: 0,
        capacity: 999,
        booked_count: 0,
        created_at: '2026-08-12T00:00:00Z',
      },
    ],
    images: [
      {
        id: 'img-jeri-001',
        trip_id: 'trip-jericoacoara-2027',
        image_url: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200&q=80',
        alt_text: 'Dunas de Jericoacoara',
        order_index: 0,
        created_at: '2026-08-12T00:00:00Z',
      },
    ],
  },
];

export const MOCK_COUPONS: Coupon[] = [
  {
    id: 'cpn-reveillon10',
    code: 'REVEILLON10',
    discount_type: 'percentage',
    discount_value: 10,
    min_purchase: 500,
    max_uses: 50,
    current_uses: 12,
    expires_at: '2026-12-28T23:59:59Z',
    is_active: true,
    created_at: '2026-08-01T00:00:00Z',
  },
  {
    id: 'cpn-aventura50',
    code: 'AVENTURA50',
    discount_type: 'fixed',
    discount_value: 50,
    min_purchase: 800,
    max_uses: 30,
    current_uses: 5,
    expires_at: '2026-12-20T23:59:59Z',
    is_active: true,
    created_at: '2026-08-01T00:00:00Z',
  },
  {
    id: 'cpn-primeira',
    code: 'PRIMEIRAVIAGEM',
    discount_type: 'percentage',
    discount_value: 15,
    min_purchase: 0,
    max_uses: 100,
    current_uses: 0,
    expires_at: '2027-06-30T23:59:59Z',
    is_active: true,
    created_at: '2026-08-01T00:00:00Z',
  },
];

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'bkg-001',
    booking_code: 'AVT-2026-A1B2C',
    trip_id: 'trip-reveillon-2026',
    user_id: 'user-001',
    accommodation_id: 'acc-pousada',
    transport_option_id: 'trp-with',
    transport_included: true,
    coupon_id: 'cpn-reveillon10',
    passenger_name: 'Maria da Silva',
    passenger_document: '123.456.789-00',
    passenger_phone: '(21) 99999-1234',
    passenger_emergency_contact: 'João da Silva',
    passenger_emergency_phone: '(21) 98888-4321',
    accommodation_price: 1490,
    transport_price: 280,
    discount_amount: 177,
    total_amount: 1593,
    payment_method: 'credit_card',
    payment_status: 'confirmed',
    payment_installments: 3,
    payment_gateway_id: 'mp_12345',
    created_at: '2026-08-15T14:30:00Z',
    updated_at: '2026-08-15T14:30:00Z',
  },
  {
    id: 'bkg-002',
    booking_code: 'AVT-2026-C3D4E',
    trip_id: 'trip-reveillon-2026',
    user_id: 'user-002',
    accommodation_id: 'acc-camping',
    transport_option_id: 'trp-without',
    transport_included: false,
    coupon_id: null,
    passenger_name: 'Pedro Santos',
    passenger_document: '987.654.321-00',
    passenger_phone: '(11) 97777-5678',
    passenger_emergency_contact: 'Ana Santos',
    passenger_emergency_phone: '(11) 96666-8765',
    accommodation_price: 890,
    transport_price: 0,
    discount_amount: 0,
    total_amount: 890,
    payment_method: 'pix',
    payment_status: 'confirmed',
    payment_installments: 1,
    payment_gateway_id: 'mp_67890',
    created_at: '2026-08-16T10:15:00Z',
    updated_at: '2026-08-16T10:15:00Z',
  },
  {
    id: 'bkg-003',
    booking_code: 'AVT-2026-F5G6H',
    trip_id: 'trip-reveillon-2026',
    user_id: 'user-003',
    accommodation_id: 'acc-suite',
    transport_option_id: 'trp-with',
    transport_included: true,
    coupon_id: 'cpn-aventura50',
    passenger_name: 'Carla Oliveira',
    passenger_document: '456.789.123-00',
    passenger_phone: '(21) 96543-2109',
    passenger_emergency_contact: 'Roberto Oliveira',
    passenger_emergency_phone: '(21) 95432-1098',
    accommodation_price: 1990,
    transport_price: 280,
    discount_amount: 50,
    total_amount: 2220,
    payment_method: 'credit_card',
    payment_status: 'confirmed',
    payment_installments: 6,
    payment_gateway_id: 'mp_11223',
    created_at: '2026-08-17T09:00:00Z',
    updated_at: '2026-08-17T09:00:00Z',
  },
  {
    id: 'bkg-004',
    booking_code: 'AVT-2026-I7J8K',
    trip_id: 'trip-reveillon-2026',
    user_id: 'user-004',
    accommodation_id: 'acc-camping',
    transport_option_id: 'trp-with',
    transport_included: true,
    coupon_id: null,
    passenger_name: 'Lucas Ferreira',
    passenger_document: '321.654.987-00',
    passenger_phone: '(21) 94321-6789',
    passenger_emergency_contact: 'Juliana Ferreira',
    passenger_emergency_phone: '(21) 93210-5678',
    accommodation_price: 890,
    transport_price: 280,
    discount_amount: 0,
    total_amount: 1170,
    payment_method: 'pix',
    payment_status: 'pending',
    payment_installments: 1,
    payment_gateway_id: '',
    created_at: '2026-08-18T16:45:00Z',
    updated_at: '2026-08-18T16:45:00Z',
  },
  {
    id: 'bkg-005',
    booking_code: 'AVT-2026-L9M0N',
    trip_id: 'trip-reveillon-2026',
    user_id: 'user-005',
    accommodation_id: 'acc-pousada',
    transport_option_id: 'trp-without',
    transport_included: false,
    coupon_id: null,
    passenger_name: 'Amanda Costa',
    passenger_document: '654.321.987-00',
    passenger_phone: '(11) 92109-8765',
    passenger_emergency_contact: 'Ricardo Costa',
    passenger_emergency_phone: '(11) 91098-7654',
    accommodation_price: 1490,
    transport_price: 0,
    discount_amount: 0,
    total_amount: 1490,
    payment_method: 'credit_card',
    payment_status: 'confirmed',
    payment_installments: 4,
    payment_gateway_id: 'mp_44556',
    created_at: '2026-08-18T20:00:00Z',
    updated_at: '2026-08-18T20:00:00Z',
  },
];
